export enum THEME {
  BLUE = "BLUE",
  GRAY = "GRAY",
  DARK_GRAY = "DARK_GRAY",
  LIGHT_BLUE = "LIGHT_BLUE",
  GREEN = "GREEN",
  RED = "RED",
  BORDER_BLUE = "BORDER_BLUE",
}

export enum DATE_FORMAT {
  YEAR_MONTH_DAY = "YYYY-MM-DD",
  DATE_TIME = "YYYY-MM-DD h:mm A",
  DAY_MONTH_YEAR = "DD/MM/YYYY",
  YEAR = "YYYY",
}
